### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by 0xMRTT** [Bavarder/Bavarder#7]
- [x] Add support for formating
  - [x] Code
  - [x] Table
- [x] Add multi chat ui
- [x] Add ability to switch backends
  - [x] Add GPT-3 - OpenAI - Require API key
  - [x] Add GPT-4 - OpenAI
  - [x] Add Hugging Chat
- [x] Add delta feature (if backend support it)
- [ ] Add Text-To-Speech
- [ ] Add Speech-To-Text
- [ ] Add file support (#12)

**Comment by jbingram** [comment]
- Is it using GPT-3 or GPT-4?
- the flathub link is down (but maybe it is too soon).
keep up the good work

**Comment by 0xMRTT** [comment]
It's using GPT-3.5 Turbo and the flathub link is down because it's not yet on flahub 

See https://github.com/flathub/flathub/pull/4109#issuecomment-1526578887 the MR to add it to flahub

**Comment by daudix-UFO** [comment]
Some UI ideas:

- Code blocks could look like in [Icon Library](https://gitlab.gnome.org/World/design/icon-library) <sup>[1](https://gitlab.gnome.org/World/design/icon-library/-/blob/master/data/resources/ui/export_dialog.ui#L292-306) [2](https://gitlab.gnome.org/World/design/icon-library/-/blob/master/data/resources/style.css#L26-28) [3](https://gitlab.gnome.org/World/design/icon-library/-/blob/master/data/resources/style.css#L34-37)</sup>

![image](https://user-images.githubusercontent.com/77155297/235322773-fa0b2412-6096-44c8-ba45-87d39a825505.png)

- Message bubbles could look like in [Telegrand](https://github.com/melix99/telegrand) <sup> [1](https://github.com/melix99/telegrand/blob/main/data/resources/style.css#L133C2-L164)</sup>

![image](https://user-images.githubusercontent.com/77155297/235322819-977bdaf8-a982-4661-ab53-135de2b71c86.png)

- Message prompt could look like in [Telegrand](https://github.com/melix99/telegrand) or [Fractal](https://gitlab.gnome.org/GNOME/fractal)

![image](https://user-images.githubusercontent.com/77155297/235322665-ae7705fb-193c-4bcb-a1cb-b27b46802202.png)

![image](https://user-images.githubusercontent.com/77155297/235322709-be781a0a-3c7c-4ce6-b47f-711ad4dc401a.png)

**Comment by 0xMRTT** [comment]
> * Is it using GPT-3 or GPT-4?
> 
>     * the flathub link is down (but maybe it is too soon).
>       keep up the good work

![image](https://user-images.githubusercontent.com/105598867/235370000-852df044-1900-4daf-a160-23a74e486fea.png)

Added GPT 3.5-turbo and GPT-4 using the OpenAI API with API Key

**Comment by 0xMRTT** [comment]
> * Is it using GPT-3 or GPT-4?
> 
>     * the flathub link is down (but maybe it is too soon).
>       keep up the good work

It's now on flathub !!!

**Comment by RasheedAZ** [comment]
> > * Is it using GPT-3 or GPT-4?
> >   
> >   * the flathub link is down (but maybe it is too soon).
> >     keep up the good work
> 
> ![image](https://user-images.githubusercontent.com/105598867/235370000-852df044-1900-4daf-a160-23a74e486fea.png)
> 
> Added GPT 3.5-turbo and GPT-4 using the OpenAI API with API Key

The drop-down to switch backends does not show up in Flathub version 0.1.2

**Comment by jbingram** [comment]
I confirm @RasheedAZ 's observation

**Comment by 0xMRTT** [comment]
Yes, this feature isn't released yet

**Comment by RasheedAZ** [comment]
> Yes, this feature isn't released yet

I think it should be clearly stated in the description what AI it's using because most Linux desktop users would be open to the Hugging Face one but cautious of GPT.

**Comment by 0xMRTT** [comment]
Yes, gonna release this soon

**Comment by 0xMRTT** [comment]
Released 0.1.3 :rocket: 

cc @RasheedAZ @jbingram

**Comment by CaptainMorgan12** [comment]
I dont like the chat bubble design due to its posychomorphism. I would say keeping it clean and simple as currently designed is great. Instead the submitted prompt text alignment could be changed or text background.

**Comment by CaptainMorgan12** [comment]
![Uploading screen_realestate.png…]()

**Comment by CaptainMorgan12** [comment]
![screen_realestate](https://user-images.githubusercontent.com/80182265/236645823-9f15386c-0bdd-423e-9341-961eed9183a2.png)

Empty space

**Comment by CaptainMorgan12** [comment]
Empty Space

![screen_realestate](https://user-images.githubusercontent.com/80182265/236646146-23408f7f-c2e7-40a2-8270-1c227a2ebe52.png)

**Comment by daudix-UFO** [comment]
The message history should be easy to see and distinguish messages from each other, removing padding is not the best idea too

**Comment by CaptainMorgan12** [comment]
Yes making it easy to see is good, padding doens't have to be removed, just reduced, based on what i indicated maybe 20% padding reduction or so could already be great right now!

**Comment by 0xMRTT** [comment]
Support for local models has been added and will be available in the next release. The documentation is available [here](https://bavarder.codeberg.page/help/local/)
